### PR TITLE
Tidy up

### PR DESCRIPTION
**Pull request by domesticmouse**
Bringing repo up to current versions

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [x] 🗑️ Chore

### CODE REVIEW

**Comment by parlough** [comment]
Maybe don't include the pubspec.lock file for the packages under [put-flutter-to-work](https://github.com/flutter/put-flutter-to-work)/[flutter_nps](https://github.com/flutter/put-flutter-to-work/tree/main/flutter_nps)/[packages](https://github.com/flutter/put-flutter-to-work/tree/main/flutter_nps/packages)? I think the

**Review by parlough — APPROVED** [review]
Looks good to me after incorporating https://github.com/flutter/put-flutter-to-work/pull/172

**Comment by parlough** [comment]
I didn't realize it would merge with the checks still failing. Sorry!

**Comment by domesticmouse** [comment]
Should we revert this and single step?

**Comment by parlough** [comment]
I think it's fine since the tests passed on https://github.com/flutter/put-flutter-to-work/pull/172

**Pull request merged**
